// default package
// Generated 25 jun. 2021 13:00:58 by Hibernate Tools 5.2.12.Final
package com.fran.eoimvc2.models.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Size;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "clientes")
public class Clientes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long id;
	private String apellido;
	private Date createAt;
	private String email;
	private String nombre;

	public Clientes() {
	}

	public Clientes(long id) {
		this.id = id;
	}

	public Clientes(long id, String apellido, Date createAt, String email, String nombre) {
		this.id = id;
		this.apellido = apellido;
		this.createAt = createAt;
		this.email = email;
		this.nombre = nombre;
	}

	@Id

//	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@NotEmpty(message = "No puede estar vacio.")
	@Column(name = "apellido", nullable = false)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_at", length = 13)
	public Date getCreateAt() {
		return this.createAt;
	}

	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	@Email(message = "El email no tiene un formato correcto.")
	@Column(name = "email", unique = true)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@NotEmpty(message = "No puede estar vacio.")
	@Size(min = 4, max = 12, message = "El tamano del nombre tiene que ser entre 4 y 12 letras.")
	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
